<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:actormapping="http://www.bonitasoft.org/ns/actormapping/6.0" xmlns:configuration="http://www.bonitasoft.org/ns/studio/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_Sg9lANXmEeyeW96xeB1hiw" name="MyDiagram1" author="marci" bonitaVersion="7.14.0" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_euSdgNXmEeyeW96xeB1hiw" name="Angariação de Clientes1">
      <elements xmi:type="process:Lane" xmi:id="_glxjkNXmEeyeW96xeB1hiw" name="Comercial">
        <elements xmi:type="process:StartEvent" xmi:id="_gEFLwNXmEeyeW96xeB1hiw" name="Angariação Cliente" outgoing="_gEFMXtXmEeyeW96xeB1hiw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gEFLwdXmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gEFLwtXmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gEFLw9XmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_gEFLyNXmEeyeW96xeB1hiw" name="Projeto é Standard?" outgoing="_gEOVtdXmEeyeW96xeB1hiw _gEOVv9XmEeyeW96xeB1hiw" incoming="_gEOV0NXmEeyeW96xeB1hiw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gEFLydXmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gEFLytXmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gEFLy9XmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndMessageEvent" xmi:id="_gEFL0NXmEeyeW96xeB1hiw" name="Pedido Proposta Standard" incoming="_gEOVtdXmEeyeW96xeB1hiw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gEFL0dXmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gEFL0tXmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gEFL09XmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_gEFL2dXmEeyeW96xeB1hiw" name="Contacto com o Cliente" outgoing="_gEOVyNXmEeyeW96xeB1hiw" incoming="_gEFMXtXmEeyeW96xeB1hiw" actor="_gEFL2NXmEeyeW96xeB1hiw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gEFL2tXmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gEFL29XmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gEFL3NXmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_gEFL3dXmEeyeW96xeB1hiw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gEFL3tXmEeyeW96xeB1hiw" name="cliente" content="cliente" type="TYPE_VARIABLE" returnType="com.company.model.Cliente">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_gEFL39XmEeyeW96xeB1hiw" name="cliente" dataType="_Sg9lNNXmEeyeW96xeB1hiw" className="com.company.model.Cliente"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gEFL4NXmEeyeW96xeB1hiw" name="clienteInput.id" content="clienteInput?.id" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_gEFL4dXmEeyeW96xeB1hiw" name="clienteInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_gEFL4tXmEeyeW96xeB1hiw" type="JAVA_METHOD" expression="setId">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_gEFL49XmEeyeW96xeB1hiw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gEFL5NXmEeyeW96xeB1hiw" name="cliente" content="cliente" type="TYPE_VARIABLE" returnType="com.company.model.Cliente">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_gEFL5dXmEeyeW96xeB1hiw" name="cliente" dataType="_Sg9lNNXmEeyeW96xeB1hiw" className="com.company.model.Cliente"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gEFL5tXmEeyeW96xeB1hiw" name="clienteInput.nome" content="clienteInput?.nome" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_gEFL59XmEeyeW96xeB1hiw" name="clienteInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_gEFL6NXmEeyeW96xeB1hiw" type="JAVA_METHOD" expression="setNome">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_gEFL6dXmEeyeW96xeB1hiw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gEFL6tXmEeyeW96xeB1hiw" name="cliente" content="cliente" type="TYPE_VARIABLE" returnType="com.company.model.Cliente">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_gEFL69XmEeyeW96xeB1hiw" name="cliente" dataType="_Sg9lNNXmEeyeW96xeB1hiw" className="com.company.model.Cliente"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gEFL7NXmEeyeW96xeB1hiw" name="clienteInput.apelido" content="clienteInput?.apelido" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_gEFL7dXmEeyeW96xeB1hiw" name="clienteInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_gEFL7tXmEeyeW96xeB1hiw" type="JAVA_METHOD" expression="setApelido">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_gEFL79XmEeyeW96xeB1hiw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gEFL8NXmEeyeW96xeB1hiw" name="cliente" content="cliente" type="TYPE_VARIABLE" returnType="com.company.model.Cliente">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_gEFL8dXmEeyeW96xeB1hiw" name="cliente" dataType="_Sg9lNNXmEeyeW96xeB1hiw" className="com.company.model.Cliente"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gEFL8tXmEeyeW96xeB1hiw" name="clienteInput.empresa" content="clienteInput?.empresa" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_gEFL89XmEeyeW96xeB1hiw" name="clienteInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_gEFL9NXmEeyeW96xeB1hiw" type="JAVA_METHOD" expression="setEmpresa">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_gEFL9dXmEeyeW96xeB1hiw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gEFL9tXmEeyeW96xeB1hiw" name="idCliente" content="idCliente" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_gEFL99XmEeyeW96xeB1hiw" name="idCliente" dataType="_Sg9lMdXmEeyeW96xeB1hiw"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gEFL-NXmEeyeW96xeB1hiw" name="newScript()" content="clienteInput" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_gEFL-dXmEeyeW96xeB1hiw" name="clienteInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_gEFL-tXmEeyeW96xeB1hiw" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_gEFL-9XmEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_gEFL_NXmEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_gEFL_dXmEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_gEFL_tXmEeyeW96xeB1hiw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_gEFL_9XmEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_gEFMANXmEeyeW96xeB1hiw">
            <targetForm xmi:type="expression:Expression" xmi:id="_gEFMAdXmEeyeW96xeB1hiw" name="CriarCliente" content="dab29ece-8ebf-4dc1-8979-b809ad4ecd2f" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_gEFMAtXmEeyeW96xeB1hiw">
            <inputs xmi:type="process:ContractInput" xmi:id="_gEFMA9XmEeyeW96xeB1hiw" name="clienteInput" type="COMPLEX" dataReference="cliente" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_gEFMBNXmEeyeW96xeB1hiw" name="id" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_gEFMBdXmEeyeW96xeB1hiw" name="nome" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_gEFMBtXmEeyeW96xeB1hiw" name="apelido" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_gEFMB9XmEeyeW96xeB1hiw" name="empresa" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_gEFMCNXmEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndMessageEvent" xmi:id="_gEFMDNXmEeyeW96xeB1hiw" name="Envio Projeto Suporte" incoming="_gEOV2NXmEeyeW96xeB1hiw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gEFMDdXmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gEFMDtXmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gEFMD9XmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_gEFMFNXmEeyeW96xeB1hiw" name="Tipo de Projeto?" outgoing="_gEOV0NXmEeyeW96xeB1hiw _gEOV2NXmEeyeW96xeB1hiw" incoming="_gEOV4tXmEeyeW96xeB1hiw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gEFMFdXmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gEFMFtXmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gEFMF9XmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndMessageEvent" xmi:id="_gEFMHNXmEeyeW96xeB1hiw" name="Envio Necessidades Projeto Standard" incoming="_gEOVv9XmEeyeW96xeB1hiw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gEFMHdXmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gEFMHtXmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gEFMH9XmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_gEFMJNXmEeyeW96xeB1hiw" name="Recolha das Necessidades do cliente" outgoing="_gEOV4tXmEeyeW96xeB1hiw" incoming="_gEOVyNXmEeyeW96xeB1hiw" actor="_gEFL2NXmEeyeW96xeB1hiw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gEFMJdXmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gEFMJtXmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gEFMJ9XmEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_gEFMKNXmEeyeW96xeB1hiw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gEFMKdXmEeyeW96xeB1hiw" name="projeto" content="projeto" type="TYPE_VARIABLE" returnType="com.company.model.Projeto">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_gEFMKtXmEeyeW96xeB1hiw" name="projeto" dataType="_Sg9lNNXmEeyeW96xeB1hiw" className="com.company.model.Projeto"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gEFMK9XmEeyeW96xeB1hiw" name="projetoInput.id" content="projetoInput?.id" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_gEFMLNXmEeyeW96xeB1hiw" name="projetoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_gEFMLdXmEeyeW96xeB1hiw" type="JAVA_METHOD" expression="setId">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_gEFMLtXmEeyeW96xeB1hiw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gEFML9XmEeyeW96xeB1hiw" name="projeto" content="projeto" type="TYPE_VARIABLE" returnType="com.company.model.Projeto">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_gEFMMNXmEeyeW96xeB1hiw" name="projeto" dataType="_Sg9lNNXmEeyeW96xeB1hiw" className="com.company.model.Projeto"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gEFMMdXmEeyeW96xeB1hiw" name="projetoInput.tipoProjeto" content="projetoInput?.tipoProjeto" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_gEFMMtXmEeyeW96xeB1hiw" name="projetoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_gEFMM9XmEeyeW96xeB1hiw" type="JAVA_METHOD" expression="setTipoProjeto">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_gEFMNNXmEeyeW96xeB1hiw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gEFMNdXmEeyeW96xeB1hiw" name="projeto" content="projeto" type="TYPE_VARIABLE" returnType="com.company.model.Projeto">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_gEFMNtXmEeyeW96xeB1hiw" name="projeto" dataType="_Sg9lNNXmEeyeW96xeB1hiw" className="com.company.model.Projeto"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gEFMN9XmEeyeW96xeB1hiw" name="projetoInput.necessidades" content="def necessidadeList = []&#xD;&#xA;//For each item collected in multiple input&#xD;&#xA;projetoInput?.necessidades.each{&#xD;&#xA;&#x9;//Add Necessidade instance&#xD;&#xA;&#x9;necessidadeList.add({ currentNecessidadeInput ->&#xD;&#xA;&#x9;&#x9;def necessidadeVar = projeto.necessidades.find { it.persistenceId.toString() == currentNecessidadeInput.persistenceId_string} ?: new com.company.model.Necessidade()&#xD;&#xA;&#x9;&#x9;necessidadeVar.descricao = currentNecessidadeInput.descricao&#xD;&#xA;&#x9;&#x9;return necessidadeVar&#xD;&#xA;&#x9;}(it))&#xD;&#xA;}&#xD;&#xA;return necessidadeList" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_gEFMONXmEeyeW96xeB1hiw" name="projetoInput" type="COMPLEX" createMode="false"/>
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_gEFMOdXmEeyeW96xeB1hiw" name="projeto" dataType="_Sg9lNNXmEeyeW96xeB1hiw" className="com.company.model.Projeto"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_gEFMOtXmEeyeW96xeB1hiw" type="JAVA_METHOD" expression="setNecessidades">
              <inputTypes>java.util.List</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_gEFMO9XmEeyeW96xeB1hiw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gEFMPNXmEeyeW96xeB1hiw" name="projeto" content="projeto" type="TYPE_VARIABLE" returnType="com.company.model.Projeto">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_gEFMPdXmEeyeW96xeB1hiw" name="projeto" dataType="_Sg9lNNXmEeyeW96xeB1hiw" className="com.company.model.Projeto"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gEFMPtXmEeyeW96xeB1hiw" name="projetoInput.cliente" content="//Retrieve aggregated Cliente using its DAO and persistenceId&#xD;&#xA;def clienteVar = clienteDAO.findByPersistenceId(projetoInput?.cliente?.persistenceId_string?.trim() ? projetoInput.cliente.persistenceId_string.toLong() : null)&#xD;&#xA;if (!clienteVar) {&#xD;&#xA;&#x9;if (projetoInput?.cliente?.persistenceId_string?.trim() ? projetoInput.cliente.persistenceId_string.toLong() : null) {&#xD;&#xA;&#x9;&#x9;throw new IllegalArgumentException(&quot;The aggregated reference of type `Cliente` with the persistence id &quot; + projetoInput?.cliente?.persistenceId_string?.trim() ? projetoInput.cliente.persistenceId_string.toLong() : null + &quot; has not been found.&quot;)&#xD;&#xA;&#x9;}&#xD;&#xA;&#x9;return null&#xD;&#xA;}&#xD;&#xA;return clienteVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Cliente">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_gEFMP9XmEeyeW96xeB1hiw" name="projetoInput" type="COMPLEX" createMode="false"/>
              <referencedElements xmi:type="expression:Expression" xmi:id="_gEFMQNXmEeyeW96xeB1hiw" name="clienteDAO" content="clienteDAO" type="TYPE_BUSINESS_OBJECT_DAO" returnType="com.company.model.ClienteDAO" returnTypeFixed="true"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_gEFMQdXmEeyeW96xeB1hiw" type="JAVA_METHOD" expression="setCliente">
              <inputTypes>com.company.model.Cliente</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_gEFMQtXmEeyeW96xeB1hiw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gEFMQ9XmEeyeW96xeB1hiw" name="projeto" content="projeto" type="TYPE_VARIABLE" returnType="com.company.model.Projeto">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_gEFMRNXmEeyeW96xeB1hiw" name="projeto" dataType="_Sg9lNNXmEeyeW96xeB1hiw" className="com.company.model.Projeto"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gEFMRdXmEeyeW96xeB1hiw" name="projetoInput.standart" content="projetoInput?.standart" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_gEFMRtXmEeyeW96xeB1hiw" name="projetoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_gEFMR9XmEeyeW96xeB1hiw" type="JAVA_METHOD" expression="setStandart">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_gEFMSNXmEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_gEFMSdXmEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_gEFMStXmEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_gEFMS9XmEeyeW96xeB1hiw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_gEFMTNXmEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_gEFMTdXmEeyeW96xeB1hiw">
            <targetForm xmi:type="expression:Expression" xmi:id="_gEFMTtXmEeyeW96xeB1hiw" name="criarProjeto" content="6b768c25-8af1-4f71-8992-918f4b2e6f6e" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_gEFMT9XmEeyeW96xeB1hiw">
            <inputs xmi:type="process:ContractInput" xmi:id="_gEFMUNXmEeyeW96xeB1hiw" name="projetoInput" type="COMPLEX" dataReference="projeto" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_gEFMUdXmEeyeW96xeB1hiw" name="id" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_gEFMUtXmEeyeW96xeB1hiw" name="tipoProjeto" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_gEFMU9XmEeyeW96xeB1hiw" name="necessidades" type="COMPLEX" multiple="true" createMode="false">
                <inputs xmi:type="process:ContractInput" xmi:id="_gEFMVNXmEeyeW96xeB1hiw" name="persistenceId_string" createMode="false"/>
                <inputs xmi:type="process:ContractInput" xmi:id="_gEFMVdXmEeyeW96xeB1hiw" name="descricao" createMode="false"/>
              </inputs>
              <inputs xmi:type="process:ContractInput" xmi:id="_gEFMVtXmEeyeW96xeB1hiw" name="cliente" type="COMPLEX" createMode="false">
                <inputs xmi:type="process:ContractInput" xmi:id="_gEFMV9XmEeyeW96xeB1hiw" name="persistenceId_string" createMode="false"/>
              </inputs>
              <inputs xmi:type="process:ContractInput" xmi:id="_gEFMWNXmEeyeW96xeB1hiw" name="standart" type="BOOLEAN" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_gEFMWdXmEeyeW96xeB1hiw" expression="!projetoInput?.cliente || projetoInput?.cliente?.persistenceId_string" errorMessage="Cliente must reference an existing instance with a persistenceId for Projeto" name="aggregation_projetoInput_cliente">
              <inputNames>projetoInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_gEFMWtXmEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_r807YNXmEeyeW96xeB1hiw" name="projeto" dataType="_Sg9lNNXmEeyeW96xeB1hiw" className="com.company.model.Projeto">
        <defaultValue xmi:type="expression:Expression" xmi:id="_r807YdXmEeyeW96xeB1hiw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_stzsYNXmEeyeW96xeB1hiw" name="cliente" dataType="_Sg9lNNXmEeyeW96xeB1hiw" className="com.company.model.Cliente">
        <defaultValue xmi:type="expression:Expression" xmi:id="_stzsYdXmEeyeW96xeB1hiw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_euSdkNXmEeyeW96xeB1hiw">
        <targetForm xmi:type="expression:Expression" xmi:id="_Y5L14NXnEeyeW96xeB1hiw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_euSdktXmEeyeW96xeB1hiw">
        <targetForm xmi:type="expression:Expression" xmi:id="_euSdk9XmEeyeW96xeB1hiw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gEFMXtXmEeyeW96xeB1hiw" target="_gEFL2dXmEeyeW96xeB1hiw" source="_gEFLwNXmEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gEFMX9XmEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_gEFMYNXmEeyeW96xeB1hiw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gEOVtdXmEeyeW96xeB1hiw" target="_gEFL0NXmEeyeW96xeB1hiw" source="_gEFLyNXmEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gEOVttXmEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_gEOVt9XmEeyeW96xeB1hiw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gEOVv9XmEeyeW96xeB1hiw" target="_gEFMHNXmEeyeW96xeB1hiw" source="_gEFLyNXmEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gEOVwNXmEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_gEOVwdXmEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gEOVyNXmEeyeW96xeB1hiw" target="_gEFMJNXmEeyeW96xeB1hiw" source="_gEFL2dXmEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gEOVydXmEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_gEOVytXmEeyeW96xeB1hiw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gEOV0NXmEeyeW96xeB1hiw" target="_gEFLyNXmEeyeW96xeB1hiw" source="_gEFMFNXmEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gEOV0dXmEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_gEOV0tXmEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gEOV2NXmEeyeW96xeB1hiw" target="_gEFMDNXmEeyeW96xeB1hiw" source="_gEFMFNXmEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gEOV2dXmEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_gEOV2tXmEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gEOV4tXmEeyeW96xeB1hiw" target="_gEFMFNXmEeyeW96xeB1hiw" source="_gEFMJNXmEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gEOV49XmEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_gEOV5NXmEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_gEFL2NXmEeyeW96xeB1hiw" name="Comercial"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="_tjQtsNXmEeyeW96xeB1hiw" name="Production" version="7.12.0-004" username="walter.bates" password="bpm">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_tjQtt9XmEeyeW96xeB1hiw">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_tjQtuNXmEeyeW96xeB1hiw" name="Comercial">
            <groups xmi:type="actormapping:Groups" xmi:id="_tjQtudXmEeyeW96xeB1hiw"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_tjQtutXmEeyeW96xeB1hiw"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_tjQtu9XmEeyeW96xeB1hiw"/>
            <users xmi:type="actormapping:Users" xmi:id="_tjQtvNXmEeyeW96xeB1hiw">
              <user>comercial</user>
            </users>
          </actorMapping>
        </actorMappings>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_tjQtsdXmEeyeW96xeB1hiw" id="CONNECTOR"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_tjQtstXmEeyeW96xeB1hiw" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_tjQts9XmEeyeW96xeB1hiw" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_tjQttNXmEeyeW96xeB1hiw" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_tjQttdXmEeyeW96xeB1hiw" id="GROOVY_SCRIPT"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_tjQtttXmEeyeW96xeB1hiw" id="OTHER"/>
      </configurations>
      <contract xmi:type="process:Contract" xmi:id="_euSdlNXmEeyeW96xeB1hiw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_euSdgdXmEeyeW96xeB1hiw">
        <name xmi:type="expression:Expression" xmi:id="_euSdgtXmEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_euSdg9XmEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_euSdhNXmEeyeW96xeB1hiw">
        <name xmi:type="expression:Expression" xmi:id="_euSdhdXmEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_euSdhtXmEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_euSdh9XmEeyeW96xeB1hiw">
        <name xmi:type="expression:Expression" xmi:id="_euSdiNXmEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_euSdidXmEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_euSditXmEeyeW96xeB1hiw">
        <name xmi:type="expression:Expression" xmi:id="_euSdi9XmEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_euSdjNXmEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_euSdjdXmEeyeW96xeB1hiw">
        <name xmi:type="expression:Expression" xmi:id="_euSdjtXmEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_euSdj9XmEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_3AuRMNXnEeyeW96xeB1hiw" name="Pool1">
      <elements xmi:type="process:StartEvent" xmi:id="_4NuP0NXnEeyeW96xeB1hiw" name="Pedido de Fatura" outgoing="_4NuQBtXnEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_4NuP0dXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_4NuP0tXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_4NuP09XnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_4NuP2NXnEeyeW96xeB1hiw" name="Faturação Terminada" incoming="_4NuQJNXnEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_4NuP2dXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_4NuP2tXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_4NuP29XnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:CallActivity" xmi:id="_4NuP4NXnEeyeW96xeB1hiw" name="Confirmação " outgoing="_4NuQENXnEeyeW96xeB1hiw" incoming="_4NuQGtXnEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_4NuP4dXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_4NuP4tXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_4NuP49XnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_4NuP5NXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_4NuP5dXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4NuP5tXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_4NuP59XnEeyeW96xeB1hiw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_4NuP6NXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <calledActivityName xmi:type="expression:Expression" xmi:id="_4NuP6dXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <calledActivityVersion xmi:type="expression:Expression" xmi:id="_4NuP6tXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_4NuP7tXnEeyeW96xeB1hiw" name="Realização das faturas em vigor" outgoing="_4NuQGtXnEeyeW96xeB1hiw" incoming="_4NuQBtXnEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_4NuP79XnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_4NuP8NXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_4NuP8dXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_4NuP8tXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_4NuP89XnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4NuP9NXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_4NuP9dXnEeyeW96xeB1hiw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_4NuP9tXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:SendTask" xmi:id="_4NuP-tXnEeyeW96xeB1hiw" name="Envio da fatura ao cliente" outgoing="_4NuQJNXnEeyeW96xeB1hiw" incoming="_4NuQENXnEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_4NuP-9XnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_4NuP_NXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_4NuP_dXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_4NuP_tXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_4NuP_9XnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4NuQANXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_4NuQAdXnEeyeW96xeB1hiw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_4NuQAtXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_3AuRQNXnEeyeW96xeB1hiw">
        <targetForm xmi:type="expression:Expression" xmi:id="_3AuRQdXnEeyeW96xeB1hiw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_3A4CMNXnEeyeW96xeB1hiw">
        <targetForm xmi:type="expression:Expression" xmi:id="_3A4CMdXnEeyeW96xeB1hiw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4NuQBtXnEeyeW96xeB1hiw" target="_4NuP7tXnEeyeW96xeB1hiw" source="_4NuP0NXnEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4NuQB9XnEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_4NuQCNXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4NuQENXnEeyeW96xeB1hiw" target="_4NuP-tXnEeyeW96xeB1hiw" source="_4NuP4NXnEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4NuQEdXnEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_4NuQEtXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4NuQGtXnEeyeW96xeB1hiw" target="_4NuP4NXnEeyeW96xeB1hiw" source="_4NuP7tXnEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4NuQG9XnEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_4NuQHNXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4NuQJNXnEeyeW96xeB1hiw" target="_4NuP2NXnEeyeW96xeB1hiw" source="_4NuP-tXnEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4NuQJdXnEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_4NuQJtXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <contract xmi:type="process:Contract" xmi:id="_3A4CMtXnEeyeW96xeB1hiw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_3AuRMdXnEeyeW96xeB1hiw">
        <name xmi:type="expression:Expression" xmi:id="_3AuRMtXnEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_3AuRM9XnEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_3AuRNNXnEeyeW96xeB1hiw">
        <name xmi:type="expression:Expression" xmi:id="_3AuRNdXnEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_3AuRNtXnEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_3AuRN9XnEeyeW96xeB1hiw">
        <name xmi:type="expression:Expression" xmi:id="_3AuRONXnEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_3AuROdXnEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_3AuROtXnEeyeW96xeB1hiw">
        <name xmi:type="expression:Expression" xmi:id="_3AuRO9XnEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_3AuRPNXnEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_3AuRPdXnEeyeW96xeB1hiw">
        <name xmi:type="expression:Expression" xmi:id="_3AuRPtXnEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_3AuRP9XnEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_7fp6oNXnEeyeW96xeB1hiw" name="Orçamentos">
      <elements xmi:type="process:EndEvent" xmi:id="_8vnGoNXnEeyeW96xeB1hiw" name="Conclusão dos Desvios Orçamentais" incoming="_8vw3xdXnEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_8vnGodXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_8vnGotXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_8vnGo9XnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_8vnGqNXnEeyeW96xeB1hiw" name="Notificar comercial para executar tarefa" outgoing="_8vnHDNXnEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_8vnGqdXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_8vnGqtXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_8vnGq9XnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_8vnGrNXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_8vnGrdXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8vnGrtXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_8vnGr9XnEeyeW96xeB1hiw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_8vnGsNXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndMessageEvent" xmi:id="_8vnGtNXnEeyeW96xeB1hiw" name="Recebe termino do projeto">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_8vnGtdXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_8vnGttXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_8vnGt9XnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_8vnGvNXnEeyeW96xeB1hiw" name="Passagem para a equipa de gestão de clientes" outgoing="_8vnHFtXnEeyeW96xeB1hiw" incoming="_8vnHMtXnEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_8vnGvdXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_8vnGvtXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_8vnGv9XnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_8vnGwNXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_8vnGwdXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8vnGwtXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_8vnGw9XnEeyeW96xeB1hiw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_8vnGxNXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_8vnGyNXnEeyeW96xeB1hiw" name="Avaliação de desempenho" outgoing="_8vnHH9XnEeyeW96xeB1hiw" incoming="_8vw3u9XnEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_8vnGydXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_8vnGytXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_8vnGy9XnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_8vnGzNXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_8vnGzdXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8vnGztXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_8vnGz9XnEeyeW96xeB1hiw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_8vnG0NXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ANDGateway" xmi:id="_8vnG1NXnEeyeW96xeB1hiw" name="Copy of " outgoing="_8vnHKdXnEeyeW96xeB1hiw" incoming="_8vnHFtXnEeyeW96xeB1hiw _8vw3sdXnEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_8vnG1dXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_8vnG1tXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_8vnG19XnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ANDGateway" xmi:id="_8vnG3NXnEeyeW96xeB1hiw" name="Copy of Copy of " outgoing="_8vnHMtXnEeyeW96xeB1hiw _8vw3p9XnEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_8vnG3dXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_8vnG3tXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_8vnG39XnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_8vnG5NXnEeyeW96xeB1hiw" name="Apurar desvios de orçamentos e prazos de execução" outgoing="_8vw3sdXnEeyeW96xeB1hiw" incoming="_8vnHDNXnEeyeW96xeB1hiw _8vw3p9XnEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_8vnG5dXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_8vnG5tXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_8vnG59XnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_8vnG6NXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_8vnG6dXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8vnG6tXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_8vnG69XnEeyeW96xeB1hiw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_8vnG7NXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_8vnG7dXnEeyeW96xeB1hiw">
          <targetForm xmi:type="expression:Expression" xmi:id="_8vnG7tXnEeyeW96xeB1hiw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_8vnG79XnEeyeW96xeB1hiw"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_8vnG8NXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_8vnG9NXnEeyeW96xeB1hiw" name="Registar desvios" outgoing="_8vw3u9XnEeyeW96xeB1hiw" incoming="_8vnHKdXnEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_8vnG9dXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_8vnG9tXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_8vnG99XnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_8vnG-NXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_8vnG-dXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8vnG-tXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_8vnG-9XnEeyeW96xeB1hiw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_8vnG_NXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_8vnHANXnEeyeW96xeB1hiw" name="Atribuição de prémios/comissões" outgoing="_8vw3xdXnEeyeW96xeB1hiw" incoming="_8vnHH9XnEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_8vnHAdXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_8vnHAtXnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_8vnHA9XnEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_8vnHBNXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_8vnHBdXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8vnHBtXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_8vnHB9XnEeyeW96xeB1hiw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_8vnHCNXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_7fp6sNXnEeyeW96xeB1hiw">
        <targetForm xmi:type="expression:Expression" xmi:id="_7fp6sdXnEeyeW96xeB1hiw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_7fp6stXnEeyeW96xeB1hiw">
        <targetForm xmi:type="expression:Expression" xmi:id="_7fp6s9XnEeyeW96xeB1hiw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8vnHDNXnEeyeW96xeB1hiw" target="_8vnG5NXnEeyeW96xeB1hiw" source="_8vnGqNXnEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8vnHDdXnEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_8vnHDtXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8vnHFtXnEeyeW96xeB1hiw" target="_8vnG1NXnEeyeW96xeB1hiw" source="_8vnGvNXnEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8vnHF9XnEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_8vnHGNXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8vnHH9XnEeyeW96xeB1hiw" target="_8vnHANXnEeyeW96xeB1hiw" source="_8vnGyNXnEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8vnHINXnEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_8vnHIdXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8vnHKdXnEeyeW96xeB1hiw" target="_8vnG9NXnEeyeW96xeB1hiw" source="_8vnG1NXnEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8vnHKtXnEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_8vnHK9XnEeyeW96xeB1hiw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8vnHMtXnEeyeW96xeB1hiw" target="_8vnGvNXnEeyeW96xeB1hiw" source="_8vnG3NXnEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8vnHM9XnEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_8vnHNNXnEeyeW96xeB1hiw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8vw3p9XnEeyeW96xeB1hiw" target="_8vnG5NXnEeyeW96xeB1hiw" source="_8vnG3NXnEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8vw3qNXnEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_8vw3qdXnEeyeW96xeB1hiw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8vw3sdXnEeyeW96xeB1hiw" target="_8vnG1NXnEeyeW96xeB1hiw" source="_8vnG5NXnEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8vw3stXnEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_8vw3s9XnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8vw3u9XnEeyeW96xeB1hiw" target="_8vnGyNXnEeyeW96xeB1hiw" source="_8vnG9NXnEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8vw3vNXnEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_8vw3vdXnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8vw3xdXnEeyeW96xeB1hiw" target="_8vnGoNXnEeyeW96xeB1hiw" source="_8vnHANXnEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8vw3xtXnEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_8vw3x9XnEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <contract xmi:type="process:Contract" xmi:id="_7fp6tNXnEeyeW96xeB1hiw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_7fp6odXnEeyeW96xeB1hiw">
        <name xmi:type="expression:Expression" xmi:id="_7fp6otXnEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_7fp6o9XnEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_7fp6pNXnEeyeW96xeB1hiw">
        <name xmi:type="expression:Expression" xmi:id="_7fp6pdXnEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_7fp6ptXnEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_7fp6p9XnEeyeW96xeB1hiw">
        <name xmi:type="expression:Expression" xmi:id="_7fp6qNXnEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_7fp6qdXnEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_7fp6qtXnEeyeW96xeB1hiw">
        <name xmi:type="expression:Expression" xmi:id="_7fp6q9XnEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_7fp6rNXnEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_7fp6rdXnEeyeW96xeB1hiw">
        <name xmi:type="expression:Expression" xmi:id="_7fp6rtXnEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_7fp6r9XnEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_CxwPQNXoEeyeW96xeB1hiw" name="Execução de Projeto">
      <elements xmi:type="process:Task" xmi:id="_EOqSINXoEeyeW96xeB1hiw" name="Execução Projeto" outgoing="_EOvKoNXoEeyeW96xeB1hiw" incoming="_EOvKtNXoEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_EOqSIdXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_EOqSItXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_EOqSI9XoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_EOqSJNXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_EOqSJdXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_EOqSJtXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_EOqSJ9XoEeyeW96xeB1hiw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_EOqSKNXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <BoundaryIntermediateEvents xmi:type="process:NonInterruptingBoundaryTimerEvent" xmi:id="_EOqSKdXoEeyeW96xeB1hiw" name="Entrega de deliver pedido pelo cliente" outgoing="_EOvK5NXoEeyeW96xeB1hiw"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_EOqSKtXoEeyeW96xeB1hiw">
          <targetForm xmi:type="expression:Expression" xmi:id="_EOqSK9XoEeyeW96xeB1hiw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_EOqSLNXoEeyeW96xeB1hiw"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_EOqSLdXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_EOqSOdXoEeyeW96xeB1hiw" name="Copy of Copy of Copy of " incoming="_EOvKqtXoEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_EOqSOtXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_EOqSO9XoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_EOqSPNXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:CallActivity" xmi:id="_EOqSQdXoEeyeW96xeB1hiw" name="Faturação" outgoing="_EOvKqtXoEeyeW96xeB1hiw" incoming="_EOvK5NXoEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_EOqSQtXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_EOqSQ9XoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_EOqSRNXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_EOqSRdXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_EOqSRtXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_EOqSR9XoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_EOqSSNXoEeyeW96xeB1hiw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_EOqSSdXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <calledActivityName xmi:type="expression:Expression" xmi:id="_EOqSStXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <calledActivityVersion xmi:type="expression:Expression" xmi:id="_EOqSS9XoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_EOqST9XoEeyeW96xeB1hiw" name="Montagem de equipa" outgoing="_EOvKtNXoEeyeW96xeB1hiw" incoming="_EOvKvtXoEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_EOqSUNXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_EOqSUdXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_EOqSUtXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_EOqSU9XoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_EOqSVNXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_EOqSVdXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_EOqSVtXoEeyeW96xeB1hiw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_EOqSV9XoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndMessageEvent" xmi:id="_EOqSW9XoEeyeW96xeB1hiw" name="Projeto Concluído" incoming="_EOvKoNXoEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_EOqSXNXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_EOqSXdXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_EOqSXtXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_EOqSY9XoEeyeW96xeB1hiw" name="Reunião com o comercial" outgoing="_EOvKvtXoEeyeW96xeB1hiw" incoming="_EOvK2tXoEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_EOqSZNXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_EOqSZdXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_EOqSZtXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_EOqSZ9XoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_EOqSaNXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_EOqSadXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_EOqSatXoEeyeW96xeB1hiw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_EOqSa9XoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_EOqSb9XoEeyeW96xeB1hiw" name="Identificação gestor projeto" outgoing="_EOvKyNXoEeyeW96xeB1hiw" incoming="_EOvK0NXoEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_EOqScNXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_EOqScdXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_EOqSctXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_EOqSc9XoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_EOqSdNXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_EOqSddXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_EOqSdtXoEeyeW96xeB1hiw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_EOqSd9XoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:StartMessageEvent" xmi:id="_EOqSe9XoEeyeW96xeB1hiw" name="Recebe Proposta" outgoing="_EOvK0NXoEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_EOqSfNXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_EOqSfdXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_EOqSftXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_EOqSg9XoEeyeW96xeB1hiw" name="Notificação comercial e gestor para reunir" outgoing="_EOvK2tXoEeyeW96xeB1hiw" incoming="_EOvKyNXoEeyeW96xeB1hiw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_EOqShNXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_EOqShdXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_EOqShtXoEeyeW96xeB1hiw" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_EOqSh9XoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_EOqSiNXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_EOqSidXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_EOqSitXoEeyeW96xeB1hiw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_EOqSi9XoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_CxwPUNXoEeyeW96xeB1hiw">
        <targetForm xmi:type="expression:Expression" xmi:id="_CxwPUdXoEeyeW96xeB1hiw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_CxwPUtXoEeyeW96xeB1hiw">
        <targetForm xmi:type="expression:Expression" xmi:id="_CxwPU9XoEeyeW96xeB1hiw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EOvKoNXoEeyeW96xeB1hiw" target="_EOqSW9XoEeyeW96xeB1hiw" source="_EOqSINXoEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EOvKodXoEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_EOvKotXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EOvKqtXoEeyeW96xeB1hiw" target="_EOqSOdXoEeyeW96xeB1hiw" source="_EOqSQdXoEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EOvKq9XoEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_EOvKrNXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EOvKtNXoEeyeW96xeB1hiw" target="_EOqSINXoEeyeW96xeB1hiw" source="_EOqST9XoEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EOvKtdXoEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_EOvKttXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EOvKvtXoEeyeW96xeB1hiw" target="_EOqST9XoEeyeW96xeB1hiw" source="_EOqSY9XoEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EOvKv9XoEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_EOvKwNXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EOvKyNXoEeyeW96xeB1hiw" target="_EOqSg9XoEeyeW96xeB1hiw" source="_EOqSb9XoEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EOvKydXoEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_EOvKytXoEeyeW96xeB1hiw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EOvK0NXoEeyeW96xeB1hiw" target="_EOqSb9XoEeyeW96xeB1hiw" source="_EOqSe9XoEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EOvK0dXoEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_EOvK0tXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EOvK2tXoEeyeW96xeB1hiw" target="_EOqSY9XoEeyeW96xeB1hiw" source="_EOqSg9XoEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EOvK29XoEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_EOvK3NXoEeyeW96xeB1hiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EOvK5NXoEeyeW96xeB1hiw" target="_EOqSQdXoEeyeW96xeB1hiw" source="_EOqSKdXoEeyeW96xeB1hiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EOvK5dXoEeyeW96xeB1hiw"/>
        <condition xmi:type="expression:Expression" xmi:id="_EOvK5tXoEeyeW96xeB1hiw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <contract xmi:type="process:Contract" xmi:id="_CxwPVNXoEeyeW96xeB1hiw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_CxwPQdXoEeyeW96xeB1hiw">
        <name xmi:type="expression:Expression" xmi:id="_CxwPQtXoEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_CxwPQ9XoEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_CxwPRNXoEeyeW96xeB1hiw">
        <name xmi:type="expression:Expression" xmi:id="_CxwPRdXoEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_CxwPRtXoEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_CxwPR9XoEeyeW96xeB1hiw">
        <name xmi:type="expression:Expression" xmi:id="_CxwPSNXoEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_CxwPSdXoEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_CxwPStXoEeyeW96xeB1hiw">
        <name xmi:type="expression:Expression" xmi:id="_CxwPS9XoEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_CxwPTNXoEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_CxwPTdXoEeyeW96xeB1hiw">
        <name xmi:type="expression:Expression" xmi:id="_CxwPTtXoEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_CxwPT9XoEeyeW96xeB1hiw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_Sg9lLNXmEeyeW96xeB1hiw" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_Sg9lLdXmEeyeW96xeB1hiw" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_Sg9lLtXmEeyeW96xeB1hiw" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_Sg9lL9XmEeyeW96xeB1hiw" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_Sg9lMNXmEeyeW96xeB1hiw" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_Sg9lMdXmEeyeW96xeB1hiw" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_Sg9lMtXmEeyeW96xeB1hiw" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_Sg9lM9XmEeyeW96xeB1hiw" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_Sg9lNNXmEeyeW96xeB1hiw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_Sg9lNdXmEeyeW96xeB1hiw" type="Process" element="_Sg9lANXmEeyeW96xeB1hiw" name="MyDiagram1" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_euSdldXmEeyeW96xeB1hiw" type="2007" element="_euSdgNXmEeyeW96xeB1hiw">
      <children xmi:type="notation:DecorationNode" xmi:id="_euSdmtXmEeyeW96xeB1hiw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_euSdm9XmEeyeW96xeB1hiw" type="7001">
        <children xmi:type="notation:Node" xmi:id="_glxjkdXmEeyeW96xeB1hiw" type="3007" element="_glxjkNXmEeyeW96xeB1hiw">
          <children xmi:type="notation:DecorationNode" xmi:id="_glxjltXmEeyeW96xeB1hiw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_glxjl9XmEeyeW96xeB1hiw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_gEFLxNXmEeyeW96xeB1hiw" type="3002" element="_gEFLwNXmEeyeW96xeB1hiw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_gEFLxdXmEeyeW96xeB1hiw" type="5024" element="_gEFLwNXmEeyeW96xeB1hiw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_gEFLxtXmEeyeW96xeB1hiw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gEFLx9XmEeyeW96xeB1hiw" x="108" y="99"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gEFLzNXmEeyeW96xeB1hiw" type="3008" element="_gEFLyNXmEeyeW96xeB1hiw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_gEFLzdXmEeyeW96xeB1hiw" type="5026" element="_gEFLyNXmEeyeW96xeB1hiw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_gEFLztXmEeyeW96xeB1hiw" x="68" y="-14"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gEFLz9XmEeyeW96xeB1hiw" x="590" y="96" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gEFL1NXmEeyeW96xeB1hiw" type="3011" element="_gEFL0NXmEeyeW96xeB1hiw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_gEFL1dXmEeyeW96xeB1hiw" type="5028" element="_gEFL0NXmEeyeW96xeB1hiw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_gEFL1tXmEeyeW96xeB1hiw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gEFL19XmEeyeW96xeB1hiw" x="698" y="49" width="30" height="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gEFMCdXmEeyeW96xeB1hiw" type="3005" element="_gEFL2dXmEeyeW96xeB1hiw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_gEFMCtXmEeyeW96xeB1hiw" type="5005" element="_gEFL2dXmEeyeW96xeB1hiw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gEFMC9XmEeyeW96xeB1hiw" x="208" y="85" width="115" height="58"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gEFMENXmEeyeW96xeB1hiw" type="3011" element="_gEFMDNXmEeyeW96xeB1hiw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_gEFMEdXmEeyeW96xeB1hiw" type="5028" element="_gEFMDNXmEeyeW96xeB1hiw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_gEFMEtXmEeyeW96xeB1hiw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gEFME9XmEeyeW96xeB1hiw" x="515" y="208"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gEFMGNXmEeyeW96xeB1hiw" type="3008" element="_gEFMFNXmEeyeW96xeB1hiw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_gEFMGdXmEeyeW96xeB1hiw" type="5026" element="_gEFMFNXmEeyeW96xeB1hiw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_gEFMGtXmEeyeW96xeB1hiw" x="1" y="-53"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gEFMG9XmEeyeW96xeB1hiw" x="508" y="92"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gEFMINXmEeyeW96xeB1hiw" type="3011" element="_gEFMHNXmEeyeW96xeB1hiw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_gEFMIdXmEeyeW96xeB1hiw" type="5028" element="_gEFMHNXmEeyeW96xeB1hiw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_gEFMItXmEeyeW96xeB1hiw" x="-33" y="9"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gEFMI9XmEeyeW96xeB1hiw" x="698" y="145"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gEFMW9XmEeyeW96xeB1hiw" type="3005" element="_gEFMJNXmEeyeW96xeB1hiw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_gEFMXNXmEeyeW96xeB1hiw" type="5005" element="_gEFMJNXmEeyeW96xeB1hiw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gEFMXdXmEeyeW96xeB1hiw" x="378" y="91" width="100" height="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_glxjktXmEeyeW96xeB1hiw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_glxjk9XmEeyeW96xeB1hiw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_glxjlNXmEeyeW96xeB1hiw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_glxjmNXmEeyeW96xeB1hiw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_glxjldXmEeyeW96xeB1hiw" x="51" y="187"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_euSdltXmEeyeW96xeB1hiw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_euSdl9XmEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_euSdmNXmEeyeW96xeB1hiw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_euSdnNXmEeyeW96xeB1hiw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_euSdmdXmEeyeW96xeB1hiw" width="1320" height="298"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_3A4CM9XnEeyeW96xeB1hiw" type="2007" element="_3AuRMNXnEeyeW96xeB1hiw">
      <children xmi:type="notation:DecorationNode" xmi:id="_3A4CONXnEeyeW96xeB1hiw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_3A4COdXnEeyeW96xeB1hiw" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_4NuP1NXnEeyeW96xeB1hiw" type="3002" element="_4NuP0NXnEeyeW96xeB1hiw" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_4NuP1dXnEeyeW96xeB1hiw" type="5024" element="_4NuP0NXnEeyeW96xeB1hiw">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_4NuP1tXnEeyeW96xeB1hiw" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4NuP19XnEeyeW96xeB1hiw" x="118" y="115"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_4NuP3NXnEeyeW96xeB1hiw" type="3003" element="_4NuP2NXnEeyeW96xeB1hiw" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_4NuP3dXnEeyeW96xeB1hiw" type="5025" element="_4NuP2NXnEeyeW96xeB1hiw">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_4NuP3tXnEeyeW96xeB1hiw" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4NuP39XnEeyeW96xeB1hiw" x="814" y="129"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_4NuP69XnEeyeW96xeB1hiw" type="3063" element="_4NuP4NXnEeyeW96xeB1hiw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_4NuP7NXnEeyeW96xeB1hiw" type="5093" element="_4NuP4NXnEeyeW96xeB1hiw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4NuP7dXnEeyeW96xeB1hiw" x="399" y="105" width="136" height="68"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_4NuP99XnEeyeW96xeB1hiw" type="3027" element="_4NuP7tXnEeyeW96xeB1hiw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_4NuP-NXnEeyeW96xeB1hiw" type="5017" element="_4NuP7tXnEeyeW96xeB1hiw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4NuP-dXnEeyeW96xeB1hiw" x="215" y="105" width="142" height="71"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_4NuQA9XnEeyeW96xeB1hiw" type="3025" element="_4NuP-tXnEeyeW96xeB1hiw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_4NuQBNXnEeyeW96xeB1hiw" type="5011" element="_4NuP-tXnEeyeW96xeB1hiw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4NuQBdXnEeyeW96xeB1hiw" x="584" y="105" width="154" height="77"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_3A4CNNXnEeyeW96xeB1hiw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_3A4CNdXnEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_3A4CNtXnEeyeW96xeB1hiw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_3A4COtXnEeyeW96xeB1hiw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3A4CN9XnEeyeW96xeB1hiw" width="1320" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_7fp6tdXnEeyeW96xeB1hiw" type="2007" element="_7fp6oNXnEeyeW96xeB1hiw">
      <children xmi:type="notation:DecorationNode" xmi:id="_7fp6utXnEeyeW96xeB1hiw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_7fp6u9XnEeyeW96xeB1hiw" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_8vnGpNXnEeyeW96xeB1hiw" type="3003" element="_8vnGoNXnEeyeW96xeB1hiw" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_8vnGpdXnEeyeW96xeB1hiw" type="5025" element="_8vnGoNXnEeyeW96xeB1hiw">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_8vnGptXnEeyeW96xeB1hiw" x="-42" y="46"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8vnGp9XnEeyeW96xeB1hiw" x="1367" y="174"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_8vnGsdXnEeyeW96xeB1hiw" type="3027" element="_8vnGqNXnEeyeW96xeB1hiw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_8vnGstXnEeyeW96xeB1hiw" type="5017" element="_8vnGqNXnEeyeW96xeB1hiw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8vnGs9XnEeyeW96xeB1hiw" x="690" y="27" width="140" height="70"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_8vnGuNXnEeyeW96xeB1hiw" type="3011" element="_8vnGtNXnEeyeW96xeB1hiw" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_8vnGudXnEeyeW96xeB1hiw" type="5028" element="_8vnGtNXnEeyeW96xeB1hiw">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_8vnGutXnEeyeW96xeB1hiw" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8vnGu9XnEeyeW96xeB1hiw" x="250" y="163"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_8vnGxdXnEeyeW96xeB1hiw" type="3027" element="_8vnGvNXnEeyeW96xeB1hiw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_8vnGxtXnEeyeW96xeB1hiw" type="5017" element="_8vnGvNXnEeyeW96xeB1hiw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8vnGx9XnEeyeW96xeB1hiw" x="442" y="228" width="174" height="87"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_8vnG0dXnEeyeW96xeB1hiw" type="3027" element="_8vnGyNXnEeyeW96xeB1hiw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_8vnG0tXnEeyeW96xeB1hiw" type="5017" element="_8vnGyNXnEeyeW96xeB1hiw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8vnG09XnEeyeW96xeB1hiw" x="958" y="153" width="144" height="72"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_8vnG2NXnEeyeW96xeB1hiw" type="3009" element="_8vnG1NXnEeyeW96xeB1hiw" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_8vnG2dXnEeyeW96xeB1hiw" type="5020" element="_8vnG1NXnEeyeW96xeB1hiw">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_8vnG2tXnEeyeW96xeB1hiw" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8vnG29XnEeyeW96xeB1hiw" x="648" y="156"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_8vnG4NXnEeyeW96xeB1hiw" type="3009" element="_8vnG3NXnEeyeW96xeB1hiw" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_8vnG4dXnEeyeW96xeB1hiw" type="5020" element="_8vnG3NXnEeyeW96xeB1hiw">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_8vnG4tXnEeyeW96xeB1hiw" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8vnG49XnEeyeW96xeB1hiw" x="359" y="156"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_8vnG8dXnEeyeW96xeB1hiw" type="3005" element="_8vnG5NXnEeyeW96xeB1hiw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_8vnG8tXnEeyeW96xeB1hiw" type="5005" element="_8vnG5NXnEeyeW96xeB1hiw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8vnG89XnEeyeW96xeB1hiw" x="435" y="60" width="175" height="88"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_8vnG_dXnEeyeW96xeB1hiw" type="3027" element="_8vnG9NXnEeyeW96xeB1hiw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_8vnG_tXnEeyeW96xeB1hiw" type="5017" element="_8vnG9NXnEeyeW96xeB1hiw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8vnG_9XnEeyeW96xeB1hiw" x="782" y="153" width="122" height="61"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_8vnHCdXnEeyeW96xeB1hiw" type="3027" element="_8vnHANXnEeyeW96xeB1hiw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_8vnHCtXnEeyeW96xeB1hiw" type="5017" element="_8vnHANXnEeyeW96xeB1hiw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8vnHC9XnEeyeW96xeB1hiw" x="1160" y="153" width="154" height="77"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_7fp6ttXnEeyeW96xeB1hiw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_7fp6t9XnEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_7fp6uNXnEeyeW96xeB1hiw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_7fp6vNXnEeyeW96xeB1hiw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7fp6udXnEeyeW96xeB1hiw" width="1507" height="375"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_CxwPVdXoEeyeW96xeB1hiw" type="2007" element="_CxwPQNXoEeyeW96xeB1hiw">
      <children xmi:type="notation:DecorationNode" xmi:id="_CxwPWtXoEeyeW96xeB1hiw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_CxwPW9XoEeyeW96xeB1hiw" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_EOqSLtXoEeyeW96xeB1hiw" type="3005" element="_EOqSINXoEeyeW96xeB1hiw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_EOqSL9XoEeyeW96xeB1hiw" type="5005" element="_EOqSINXoEeyeW96xeB1hiw"/>
          <children xmi:type="notation:Shape" xmi:id="_EOqSNdXoEeyeW96xeB1hiw" type="3064" element="_EOqSKdXoEeyeW96xeB1hiw" fontName="Segoe UI">
            <children xmi:type="notation:DecorationNode" xmi:id="_EOqSNtXoEeyeW96xeB1hiw" type="5094" element="_EOqSKdXoEeyeW96xeB1hiw">
              <layoutConstraint xmi:type="notation:Location" xmi:id="_EOqSN9XoEeyeW96xeB1hiw" x="-115" y="6"/>
            </children>
            <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EOqSONXoEeyeW96xeB1hiw" x="235" y="176"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EOqSNNXoEeyeW96xeB1hiw" x="1185" y="213" width="126" height="63"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_EOqSPdXoEeyeW96xeB1hiw" type="3003" element="_EOqSOdXoEeyeW96xeB1hiw" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_EOqSPtXoEeyeW96xeB1hiw" type="5025" element="_EOqSOdXoEeyeW96xeB1hiw">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_EOqSP9XoEeyeW96xeB1hiw" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EOqSQNXoEeyeW96xeB1hiw" x="1401" y="352"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_EOqSTNXoEeyeW96xeB1hiw" type="3063" element="_EOqSQdXoEeyeW96xeB1hiw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_EOqSTdXoEeyeW96xeB1hiw" type="5093" element="_EOqSQdXoEeyeW96xeB1hiw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EOqSTtXoEeyeW96xeB1hiw" x="1233" y="337" width="118" height="59"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_EOqSWNXoEeyeW96xeB1hiw" type="3027" element="_EOqST9XoEeyeW96xeB1hiw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_EOqSWdXoEeyeW96xeB1hiw" type="5017" element="_EOqST9XoEeyeW96xeB1hiw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EOqSWtXoEeyeW96xeB1hiw" x="1030" y="213" width="131" height="66"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_EOqSX9XoEeyeW96xeB1hiw" type="3011" element="_EOqSW9XoEeyeW96xeB1hiw" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_EOqSYNXoEeyeW96xeB1hiw" type="5028" element="_EOqSW9XoEeyeW96xeB1hiw">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_EOqSYdXoEeyeW96xeB1hiw" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EOqSYtXoEeyeW96xeB1hiw" x="1401" y="230"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_EOqSbNXoEeyeW96xeB1hiw" type="3027" element="_EOqSY9XoEeyeW96xeB1hiw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_EOqSbdXoEeyeW96xeB1hiw" type="5017" element="_EOqSY9XoEeyeW96xeB1hiw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EOqSbtXoEeyeW96xeB1hiw" x="820" y="207" width="154" height="77"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_EOqSeNXoEeyeW96xeB1hiw" type="3027" element="_EOqSb9XoEeyeW96xeB1hiw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_EOqSedXoEeyeW96xeB1hiw" type="5017" element="_EOqSb9XoEeyeW96xeB1hiw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EOqSetXoEeyeW96xeB1hiw" x="427" y="210" width="143" height="71"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_EOqSf9XoEeyeW96xeB1hiw" type="3012" element="_EOqSe9XoEeyeW96xeB1hiw" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_EOqSgNXoEeyeW96xeB1hiw" type="5029" element="_EOqSe9XoEeyeW96xeB1hiw">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_EOqSgdXoEeyeW96xeB1hiw" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EOqSgtXoEeyeW96xeB1hiw" x="316" y="231"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_EOqSjNXoEeyeW96xeB1hiw" type="3027" element="_EOqSg9XoEeyeW96xeB1hiw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_EOqSjdXoEeyeW96xeB1hiw" type="5017" element="_EOqSg9XoEeyeW96xeB1hiw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EOqSjtXoEeyeW96xeB1hiw" x="615" y="204" width="168" height="84"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_CxwPVtXoEeyeW96xeB1hiw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_CxwPV9XoEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_CxwPWNXoEeyeW96xeB1hiw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_CxwPXNXoEeyeW96xeB1hiw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_CxwPWdXoEeyeW96xeB1hiw" width="1541" height="456"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_Sg9lTdXmEeyeW96xeB1hiw"/>
    <edges xmi:type="notation:Connector" xmi:id="_gEOVsNXmEeyeW96xeB1hiw" type="4001" element="_gEFMXtXmEeyeW96xeB1hiw" source="_gEFLxNXmEeyeW96xeB1hiw" target="_gEFMCdXmEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gEOVsdXmEeyeW96xeB1hiw" type="6001" element="_gEFMXtXmEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gEOVstXmEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gEOVs9XmEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gEOVtNXmEeyeW96xeB1hiw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gEOVuNXmEeyeW96xeB1hiw" type="4001" element="_gEOVtdXmEeyeW96xeB1hiw" source="_gEFLzNXmEeyeW96xeB1hiw" target="_gEFL1NXmEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gEOVudXmEeyeW96xeB1hiw" type="6001" element="_gEOVtdXmEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gEOVutXmEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gEOVu9XmEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gEOVvNXmEeyeW96xeB1hiw" points="[-22, -27, -89, 39]$[-22, -60, -89, 6]$[65, -60, -2, 6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gEOVvdXmEeyeW96xeB1hiw" id="(1.0,0.627906976744186)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gEOVvtXmEeyeW96xeB1hiw" id="(0.06666666666666667,0.26666666666666666)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gEOVwtXmEeyeW96xeB1hiw" type="4001" element="_gEOVv9XmEeyeW96xeB1hiw" source="_gEFLzNXmEeyeW96xeB1hiw" target="_gEFMINXmEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gEOVw9XmEeyeW96xeB1hiw" type="6001" element="_gEOVv9XmEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gEOVxNXmEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gEOVxdXmEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gEOVxtXmEeyeW96xeB1hiw" points="[-22, 11, -102, -74]$[-22, 85, -102, 0]$[65, 85, -15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gEOVx9XmEeyeW96xeB1hiw" id="(1.0,0.7441860465116279)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gEOVy9XmEeyeW96xeB1hiw" type="4001" element="_gEOVyNXmEeyeW96xeB1hiw" source="_gEFMCdXmEeyeW96xeB1hiw" target="_gEFMW9XmEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gEOVzNXmEeyeW96xeB1hiw" type="6001" element="_gEOVyNXmEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gEOVzdXmEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gEOVztXmEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gEOVz9XmEeyeW96xeB1hiw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gEOV09XmEeyeW96xeB1hiw" type="4001" element="_gEOV0NXmEeyeW96xeB1hiw" source="_gEFMGNXmEeyeW96xeB1hiw" target="_gEFLzNXmEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gEOV1NXmEeyeW96xeB1hiw" type="6001" element="_gEOV0NXmEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gEOV1dXmEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gEOV1tXmEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gEOV19XmEeyeW96xeB1hiw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gEOV29XmEeyeW96xeB1hiw" type="4001" element="_gEOV2NXmEeyeW96xeB1hiw" source="_gEFMGNXmEeyeW96xeB1hiw" target="_gEFMENXmEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gEOV3NXmEeyeW96xeB1hiw" type="6001" element="_gEOV2NXmEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gEOV3dXmEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gEOV3tXmEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gEOV39XmEeyeW96xeB1hiw" points="[-21, 11, -3, -80]$[-17, 86, 1, -5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gEOV4NXmEeyeW96xeB1hiw" id="(1.0,0.6976744186046512)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gEOV4dXmEeyeW96xeB1hiw" id="(0.6,0.16666666666666666)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gEOV5dXmEeyeW96xeB1hiw" type="4001" element="_gEOV4tXmEeyeW96xeB1hiw" source="_gEFMW9XmEeyeW96xeB1hiw" target="_gEFMGNXmEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gEOV5tXmEeyeW96xeB1hiw" type="6001" element="_gEOV4tXmEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gEOV59XmEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gEOV6NXmEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gEOV6dXmEeyeW96xeB1hiw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gEOV6tXmEeyeW96xeB1hiw" id="(1.0,0.58)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gEOV69XmEeyeW96xeB1hiw" id="(0.06976744186046512,0.46511627906976744)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4NuQCdXnEeyeW96xeB1hiw" type="4001" element="_4NuQBtXnEeyeW96xeB1hiw" source="_4NuP1NXnEeyeW96xeB1hiw" target="_4NuP99XnEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4NuQCtXnEeyeW96xeB1hiw" type="6001" element="_4NuQBtXnEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4NuQC9XnEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4NuQDNXnEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4NuQDdXnEeyeW96xeB1hiw" points="[0, -15, -72, 0]$[67, -15, -5, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4NuQDtXnEeyeW96xeB1hiw" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4NuQD9XnEeyeW96xeB1hiw" id="(0.05,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4NuQE9XnEeyeW96xeB1hiw" type="4001" element="_4NuQENXnEeyeW96xeB1hiw" source="_4NuP69XnEeyeW96xeB1hiw" target="_4NuQA9XnEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4NuQFNXnEeyeW96xeB1hiw" type="6001" element="_4NuQENXnEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4NuQFdXnEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4NuQFtXnEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4NuQF9XnEeyeW96xeB1hiw" points="[0, -4, -87, 0]$[85, -4, -2, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4NuQGNXnEeyeW96xeB1hiw" id="(1.0,0.58)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4NuQGdXnEeyeW96xeB1hiw" id="(0.02,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4NuQHdXnEeyeW96xeB1hiw" type="4001" element="_4NuQGtXnEeyeW96xeB1hiw" source="_4NuP99XnEeyeW96xeB1hiw" target="_4NuP69XnEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4NuQHtXnEeyeW96xeB1hiw" type="6001" element="_4NuQGtXnEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4NuQH9XnEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4NuQINXnEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4NuQIdXnEeyeW96xeB1hiw" points="[0, -3, -85, 0]$[84, -4, -1, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4NuQItXnEeyeW96xeB1hiw" id="(1.0,0.54)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4NuQI9XnEeyeW96xeB1hiw" id="(0.01,0.48)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4NuQJ9XnEeyeW96xeB1hiw" type="4001" element="_4NuQJNXnEeyeW96xeB1hiw" source="_4NuQA9XnEeyeW96xeB1hiw" target="_4NuP3NXnEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4NuQKNXnEeyeW96xeB1hiw" type="6001" element="_4NuQJNXnEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4NuQKdXnEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4NuQKtXnEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4NuQK9XnEeyeW96xeB1hiw" points="[0, 7, -101, 0]$[99, 6, -2, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4NuQLNXnEeyeW96xeB1hiw" id="(1.0,0.56)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4NuQLdXnEeyeW96xeB1hiw" id="(0.06666666666666667,0.43333333333333335)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8vnHD9XnEeyeW96xeB1hiw" type="4001" element="_8vnHDNXnEeyeW96xeB1hiw" source="_8vnGsdXnEeyeW96xeB1hiw" target="_8vnG8dXnEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8vnHENXnEeyeW96xeB1hiw" type="6001" element="_8vnHDNXnEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8vnHEdXnEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8vnHEtXnEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8vnHE9XnEeyeW96xeB1hiw" points="[-140, -17, 125, -31]$[-308, -17, -43, -31]$[-308, 7, -43, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8vnHFNXnEeyeW96xeB1hiw" id="(1.0,0.37142857142857144)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8vnHFdXnEeyeW96xeB1hiw" id="(0.7428571428571429,0.07954545454545454)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8vnHGdXnEeyeW96xeB1hiw" type="4001" element="_8vnHFtXnEeyeW96xeB1hiw" source="_8vnGxdXnEeyeW96xeB1hiw" target="_8vnG2NXnEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8vnHGtXnEeyeW96xeB1hiw" type="6001" element="_8vnHFtXnEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8vnHG9XnEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8vnHHNXnEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8vnHHdXnEeyeW96xeB1hiw" points="[0, 16, -53, 99]$[53, 16, 0, 99]$[53, -61, 0, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8vnHHtXnEeyeW96xeB1hiw" id="(1.0,0.367816091954023)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8vnHItXnEeyeW96xeB1hiw" type="4001" element="_8vnHH9XnEeyeW96xeB1hiw" source="_8vnG0dXnEeyeW96xeB1hiw" target="_8vnHCdXnEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8vnHI9XnEeyeW96xeB1hiw" type="6001" element="_8vnHH9XnEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8vnHJNXnEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8vnHJdXnEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8vnHJtXnEeyeW96xeB1hiw" points="[0, 0, -66, 0]$[58, -1, -8, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8vnHJ9XnEeyeW96xeB1hiw" id="(1.0,0.4305555555555556)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8vnHKNXnEeyeW96xeB1hiw" id="(0.05194805194805195,0.4025974025974026)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8vnHLNXnEeyeW96xeB1hiw" type="4001" element="_8vnHKdXnEeyeW96xeB1hiw" source="_8vnG2NXnEeyeW96xeB1hiw" target="_8vnG_dXnEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8vnHLdXnEeyeW96xeB1hiw" type="6001" element="_8vnHKdXnEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8vnHLtXnEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8vnHL9XnEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8vnHMNXnEeyeW96xeB1hiw" points="[-8, 1, -160, 2]$[91, 1, -61, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8vnHMdXnEeyeW96xeB1hiw" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8vw3oNXnEeyeW96xeB1hiw" type="4001" element="_8vnHMtXnEeyeW96xeB1hiw" source="_8vnG4NXnEeyeW96xeB1hiw" target="_8vnGxdXnEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8vw3odXnEeyeW96xeB1hiw" type="6001" element="_8vnHMtXnEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8vw3otXnEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8vw3o9XnEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8vw3pNXnEeyeW96xeB1hiw" points="[-22, 15, -58, -77]$[-22, 86, -58, -6]$[34, 86, -2, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8vw3pdXnEeyeW96xeB1hiw" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8vw3ptXnEeyeW96xeB1hiw" id="(0.011494252873563218,0.5517241379310345)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8vw3qtXnEeyeW96xeB1hiw" type="4001" element="_8vw3p9XnEeyeW96xeB1hiw" source="_8vnG4NXnEeyeW96xeB1hiw" target="_8vnG8dXnEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8vw3q9XnEeyeW96xeB1hiw" type="6001" element="_8vw3p9XnEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8vw3rNXnEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8vw3rdXnEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8vw3rtXnEeyeW96xeB1hiw" points="[-22, -25, -75, 35]$[-22, -85, -75, -25]$[27, -85, -26, -25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8vw3r9XnEeyeW96xeB1hiw" id="(1.0,0.5813953488372093)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8vw3sNXnEeyeW96xeB1hiw" id="(0.14857142857142858,0.6931818181818182)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8vw3tNXnEeyeW96xeB1hiw" type="4001" element="_8vw3sdXnEeyeW96xeB1hiw" source="_8vnG8dXnEeyeW96xeB1hiw" target="_8vnG2NXnEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8vw3tdXnEeyeW96xeB1hiw" type="6001" element="_8vw3sdXnEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8vw3ttXnEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8vw3t9XnEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8vw3uNXnEeyeW96xeB1hiw" points="[0, -1, -55, -77]$[59, -1, 4, -77]$[59, 71, 4, -5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8vw3udXnEeyeW96xeB1hiw" id="(1.0,0.2840909090909091)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8vw3utXnEeyeW96xeB1hiw" id="(0.3953488372093023,0.11627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8vw3vtXnEeyeW96xeB1hiw" type="4001" element="_8vw3u9XnEeyeW96xeB1hiw" source="_8vnG_dXnEeyeW96xeB1hiw" target="_8vnG0dXnEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8vw3v9XnEeyeW96xeB1hiw" type="6001" element="_8vw3u9XnEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8vw3wNXnEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8vw3wdXnEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8vw3wtXnEeyeW96xeB1hiw" points="[0, -5, 0, -5]$[31, -5, 31, -5]$[31, 16, 31, 16]$[0, 16, 0, 16]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8vw3w9XnEeyeW96xeB1hiw" id="(1.0,0.47540983606557374)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8vw3xNXnEeyeW96xeB1hiw" id="(0.18055555555555555,0.3888888888888889)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8vw3yNXnEeyeW96xeB1hiw" type="4001" element="_8vw3xdXnEeyeW96xeB1hiw" source="_8vnHCdXnEeyeW96xeB1hiw" target="_8vnGpNXnEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8vw3ydXnEeyeW96xeB1hiw" type="6001" element="_8vw3xdXnEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8vw3ytXnEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8vw3y9XnEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8vw3zNXnEeyeW96xeB1hiw" points="[0, 12, -55, 1]$[53, 12, -2, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8vw3zdXnEeyeW96xeB1hiw" id="(1.0,0.33766233766233766)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8vw3ztXnEeyeW96xeB1hiw" id="(0.06666666666666667,0.5333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EOvKo9XoEeyeW96xeB1hiw" type="4001" element="_EOvKoNXoEeyeW96xeB1hiw" source="_EOqSLtXoEeyeW96xeB1hiw" target="_EOqSX9XoEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EOvKpNXoEeyeW96xeB1hiw" type="6001" element="_EOvKoNXoEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EOvKpdXoEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EOvKptXoEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EOvKp9XoEeyeW96xeB1hiw" points="[0, 5, -96, 0]$[93, 3, -3, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EOvKqNXoEeyeW96xeB1hiw" id="(1.0,0.4444444444444444)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EOvKqdXoEeyeW96xeB1hiw" id="(0.13333333333333333,0.3)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EOvKrdXoEeyeW96xeB1hiw" type="4001" element="_EOvKqtXoEeyeW96xeB1hiw" source="_EOqSTNXoEeyeW96xeB1hiw" target="_EOqSPdXoEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EOvKrtXoEeyeW96xeB1hiw" type="6001" element="_EOvKqtXoEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EOvKr9XoEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EOvKsNXoEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EOvKsdXoEeyeW96xeB1hiw" points="[0, 0, -50, 0]$[50, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EOvKstXoEeyeW96xeB1hiw" id="(1.0,0.4745762711864407)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EOvKs9XoEeyeW96xeB1hiw" id="(0.0,0.43333333333333335)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EOvKt9XoEeyeW96xeB1hiw" type="4001" element="_EOvKtNXoEeyeW96xeB1hiw" source="_EOqSWNXoEeyeW96xeB1hiw" target="_EOqSLtXoEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EOvKuNXoEeyeW96xeB1hiw" type="6001" element="_EOvKtNXoEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EOvKudXoEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EOvKutXoEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EOvKu9XoEeyeW96xeB1hiw" points="[0, 2, -28, 7]$[24, 2, -4, 7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EOvKvNXoEeyeW96xeB1hiw" id="(1.0,0.45454545454545453)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EOvKvdXoEeyeW96xeB1hiw" id="(0.031746031746031744,0.3968253968253968)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EOvKwdXoEeyeW96xeB1hiw" type="4001" element="_EOvKvtXoEeyeW96xeB1hiw" source="_EOqSbNXoEeyeW96xeB1hiw" target="_EOqSWNXoEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EOvKwtXoEeyeW96xeB1hiw" type="6001" element="_EOvKvtXoEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EOvKw9XoEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EOvKxNXoEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EOvKxdXoEeyeW96xeB1hiw" points="[0, 10, -56, 6]$[56, 10, 0, 6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EOvKxtXoEeyeW96xeB1hiw" id="(1.0,0.36363636363636365)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EOvKx9XoEeyeW96xeB1hiw" id="(0.0,0.3939393939393939)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EOvKy9XoEeyeW96xeB1hiw" type="4001" element="_EOvKyNXoEeyeW96xeB1hiw" source="_EOqSeNXoEeyeW96xeB1hiw" target="_EOqSjNXoEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EOvKzNXoEeyeW96xeB1hiw" type="6001" element="_EOvKyNXoEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EOvKzdXoEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EOvKztXoEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EOvKz9XoEeyeW96xeB1hiw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EOvK09XoEeyeW96xeB1hiw" type="4001" element="_EOvK0NXoEeyeW96xeB1hiw" source="_EOqSf9XoEeyeW96xeB1hiw" target="_EOqSeNXoEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EOvK1NXoEeyeW96xeB1hiw" type="6001" element="_EOvK0NXoEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EOvK1dXoEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EOvK1tXoEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EOvK19XoEeyeW96xeB1hiw" points="[-1, -13, -83, -7]$[81, -13, -1, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EOvK2NXoEeyeW96xeB1hiw" id="(1.0,0.9)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EOvK2dXoEeyeW96xeB1hiw" id="(0.006993006993006993,0.43661971830985913)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EOvK3dXoEeyeW96xeB1hiw" type="4001" element="_EOvK2tXoEeyeW96xeB1hiw" source="_EOqSjNXoEeyeW96xeB1hiw" target="_EOqSbNXoEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EOvK3tXoEeyeW96xeB1hiw" type="6001" element="_EOvK2tXoEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EOvK39XoEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EOvK4NXoEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EOvK4dXoEeyeW96xeB1hiw" points="[0, 12, -39, 5]$[37, 12, -2, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EOvK4tXoEeyeW96xeB1hiw" id="(1.0,0.34523809523809523)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EOvK49XoEeyeW96xeB1hiw" id="(0.012987012987012988,0.42857142857142855)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EOvK59XoEeyeW96xeB1hiw" type="4001" element="_EOvK5NXoEeyeW96xeB1hiw" source="_EOqSNdXoEeyeW96xeB1hiw" target="_EOqSTNXoEeyeW96xeB1hiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EOvK6NXoEeyeW96xeB1hiw" type="6001" element="_EOvK5NXoEeyeW96xeB1hiw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EOvK6dXoEeyeW96xeB1hiw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EOvK6tXoEeyeW96xeB1hiw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EOvK69XoEeyeW96xeB1hiw" points="[0, 0, -69, -69]$[0, 68, -69, -1]$[19, 68, -50, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EOvK7NXoEeyeW96xeB1hiw" id="(1.0,1.0)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
